name: Android CI

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
    tags:
      - 'v*.*.*'

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install JS deps
        run: npm ci

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"
          yes | sdkmanager --licenses

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      # --- PR: APK Debug à tester ---
      - name: Assemble Debug (PR)
        if: github.event_name == 'pull_request'
        run: |
          cd android
          ./gradlew --no-daemon assembleDebug -PnewArchEnabled=false

      - name: Upload Debug APK (PR)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: android/app/build/outputs/apk/debug/*.apk
          retention-days: 7

      # --- Push sur main/master: AAB Release ---
      - name: Bundle Release (main/master)
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        run: |
          cd android
          ./gradlew --no-daemon bundleRelease -PnewArchEnabled=false

      - name: Upload Release AAB (main/master)
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: android/app/build/outputs/bundle/release/*.aab
          retention-days: 14

      # --- Tag vX.Y.Z: Release GitHub avec asset ---
      - name: Bundle Release (tag)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          cd android
          ./gradlew --no-daemon bundleRelease -PnewArchEnabled=false

      - name: Create GitHub Release (tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: android/app/build/outputs/bundle/release/*.aab
