name: Backup on push (master only)

on:
  push:
    branches: [master]
  workflow_dispatch: {}

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git identity
        run: |
          git config user.name  "backup-bot"
          git config user.email "backup@example.com"

      - name: Setup SSH (decode base64) + print fingerprint
        env:
          KEY_B64: ${{ secrets.BACKUP_SSH_KEY_B64 }}
        run: |
          set -e
          mkdir -p ~/.ssh
          echo "$KEY_B64" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # dérive la clé publique pour vérifier l'empreinte
          ssh-keygen -y -f ~/.ssh/id_ed25519 > ~/.ssh/id_ed25519.pub
          echo "== Public key (first 60 chars) =="
          head -c 60 ~/.ssh/id_ed25519.pub; echo
          echo "== Fingerprint (doit matcher celle de GitLab Deploy Key) =="
          ssh-keygen -lf ~/.ssh/id_ed25519.pub
          # known_hosts + config
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
          cat <<EOF >> ~/.ssh/config
          Host gitlab.com
            IdentityFile ~/.ssh/id_ed25519
            IdentitiesOnly yes
          EOF

      - name: Debug remote + SSH handshake (verbose)
        env:
          BACKUP_REMOTE_URL: ${{ vars.BACKUP_REMOTE_URL }}
        run: |
          echo "BACKUP_REMOTE_URL=$BACKUP_REMOTE_URL"
          git remote add backup "$BACKUP_REMOTE_URL" || true
          git remote -v
          echo "== SSH -vvv =="
          ssh -vvv -T git@gitlab.com || true

      - name: Push master + tags + branches backup to GitLab
        env:
          BACKUP_REMOTE_URL: ${{ vars.BACKUP_REMOTE_URL }}
        run: |
          set -e
          git fetch origin --prune
          git checkout master
          git reset --hard origin/master
          git push backup master
          git push backup --tags
          git push --force backup origin/master:refs/heads/backup/master-1
          git push --force backup origin/master:refs/heads/backup/master-2
          git push --force backup origin/master:refs/heads/backup/master-3
