name: CI DEV

on:
  push:
    branches: [develop]
  pull_request:

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (npm ci)
        run: npm ci

      - name: Expo Doctor
        run: npx expo doctor

      # ---------- Gradle smoke (optionnel : seulement si android/ existe)
      - name: Setup Java (JDK 17) + Gradle cache
        if: ${{ hashFiles('android/**') != '' }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        if: ${{ hashFiles('android/**') != '' }}
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-34
            build-tools;34.0.0
            platform-tools

      - name: Gradle assembleDebug (smoke build)
        if: ${{ hashFiles('android/**') != '' }}
        working-directory: android
        run: ./gradlew --no-daemon --stacktrace assembleDebug
      # ---------- fin bloc Gradle

      - name: Setup Expo (auth via robot)
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.cliToken }}  # ton secret Expo

      - name: EAS build (dev, no-wait)
        run: npx eas build --platform android --profile development --non-interactive --no-wait
